# -*- coding: utf-8 -*-
"""streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_PuvhdXHvUcwhGnT84e42w_pKJGhYLSU
"""

requirements_content = """streamlit
pandas
numpy
plotly"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from collections import Counter, defaultdict

# --- CORE LOGIC ---
def get_dr(n):
    if n == 0: return 0
    res = n % 9
    return 9 if res == 0 else res

def polukhin_step(n):
    s_desc = int(''.join(sorted(str(n), reverse=True)))
    doubled = 2 * s_desc
    normalized = str(doubled).rstrip('0')
    return int(normalized) if normalized else 0

def trace_sequence(seed, max_steps=100):
    path = []
    seen = {}
    curr = seed
    for i in range(max_steps):
        if curr in seen:
            start_idx = seen[curr]
            return {'path': path, 'cycle': path[start_idx:], 'period': i - start_idx, 'entry': start_idx}
        seen[curr] = i
        path.append(curr)
        curr = polukhin_step(curr)
    return {'path': path, 'cycle': [], 'period': 0, 'entry': max_steps}

def generate_canonical_numbers(length, target_sum):
    results = []
    def backtrack(pos, current_digits, remaining_sum, max_digit):
        if pos == length:
            if remaining_sum == 0:
                results.append(int(''.join(str(d) for d in current_digits)))
            return
        min_digit = max(1, remaining_sum - (length - pos - 1) * 9)
        for d in range(min(max_digit, 9), min_digit - 1, -1):
            current_digits.append(d)
            backtrack(pos + 1, current_digits, remaining_sum - d, d)
            current_digits.pop()
    backtrack(0, [], target_sum, 9)
    return results

# --- UI CONFIG ---
st.set_page_config(page_title="Polukhin Explorer", page_icon="🌀", layout="wide")

st.title("🌀 Исследователь Процедуры Полухина")
st.markdown("**Цифровой Онтогенез:** Интерактивная среда для анализа самоорганизации числовых систем и фазового резонанса.")

tabs = st.tabs(["📊 Анализатор Семени", "🧬 Канонический Поиск", "⚖️ Компаратор", "🌌 Космология ГВМ"])

with tabs[0]:
    st.header("Трассировка Индивидуальных Траекторий")
    col1, col2 = st.columns([1, 3])
    with col1:
        seed_input = st.number_input("Введите начальное число (Seed):", min_value=1, value=123, step=1)
        steps_input = st.slider("Макс. шагов:", 10, 500, 100)

    res = trace_sequence(seed_input, steps_input)

    with col2:
        dr_path = [get_dr(x) for x in res['path']]
        fig = px.line(y=dr_path, x=list(range(len(dr_path))), markers=True,
                      title=f"Цифровой корень (DR) траектории семени {seed_input}",
                      labels={'x': 'Шаг', 'y': 'Digital Root'})
        fig.update_layout(yaxis=dict(tickvals=list(range(1, 10))))
        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Статистика Аттрактора")
    s_col1, s_col2, s_col3 = st.columns(3)
    s_col1.metric("Период Цикла (T)", res['period'])
    s_col2.metric("Шаг входа", res['entry'])
    s_col3.metric("Макс. разрядность", max([len(str(x)) for x in res['path']]))
    st.write("**Путь цикла:**", res['cycle'])

with tabs[1]:
    st.header("Генерация Канонических Чисел")
    st.info("Backtracking-генерация чисел с заданной суммой цифр без нулей.")
    c1, c2 = st.columns(2)
    L = c1.number_input("Разрядность (L):", 2, 10, 5)
    S = c2.number_input("Сумма цифр (S):", L, L*9, L*5)

    if st.button("Запустить сканирование"):
        candidates = generate_canonical_numbers(L, S)
        st.write(f"Найдено канонических чисел: {len(candidates)}")

        data = []
        for cand in candidates:
            t = trace_sequence(cand)
            data.append({'Seed': cand, 'Period': t['period'], 'Entry': t['entry'], 'MinVal': min(t['cycle']) if t['cycle'] else 0})

        df = pd.DataFrame(data)
        fig_scan = px.scatter(df, x='Seed', y='Entry', color='Period', size='Period',
                             hover_data=['MinVal'], title="Карта бассейнов притяжения")
        st.plotly_chart(fig_scan, use_container_width=True)

with tabs[2]:
    st.header("Сравнительный Анализ")
    compare_input = st.text_input("Введите числа через запятую:", "1, 3, 9, 27, 433221")
    seeds_to_compare = [int(x.strip()) for x in compare_input.split(",") if x.strip().isdigit()]

    if seeds_to_compare:
        comp_data = []
        for s in seeds_to_compare:
            t = trace_sequence(s)
            comp_data.append({'Seed': str(s), 'Period': t['period'], 'Entry Step': t['entry'], 'DR': get_dr(s)})

        df_comp = pd.DataFrame(comp_data)
        fig_bar = px.bar(df_comp, x='Seed', y='Entry Step', color='DR',
                        title="Сравнение скорости сходимости", barmode='group')
        st.plotly_chart(fig_bar, use_container_width=True)

with tabs[3]:
    st.header("Геометрическо-Волновая Модель")
    st.markdown("Визуализация паттерна Rule 5 (8-9-9-10) как вектора протрузии в пространстве 2Pi.")

    pattern = [8, 9, 9, 10]
    phases = np.array([0, 1, 2, 3]) * (np.pi / 2)
    magnitudes = np.array(pattern) / 9.0
    x_v = magnitudes * np.cos(phases)
    y_v = magnitudes * np.sin(phases)

    fig_gvm = go.Figure()
    for i in range(4):
        fig_gvm.add_trace(go.Scatter(x=[0, x_v[i]], y=[0, y_v[i]], mode='lines+markers', name=f'Sum {pattern[i]}'))

    fig_gvm.update_layout(title="Векторная модель Rule 5", showlegend=True, width=600, height=600)
    st.plotly_chart(fig_gvm)